activation: gelu
drop_path: 0.2
edge_act_dropout: 0.1
edge_ffn_multiplier: 1.0
edge_width: 256
embed_3d_type: gaussian
layer_multiplier: 1
model_height: 24
node_act_dropout: 0.1
node_ffn_multiplier: 1.0
node_width: 512
num_3d_kernels: 128
num_heads: 8
scale_degree: true
source_dropout: 0.3
triplet_dropout: 0
triplet_heads: 8
triplet_type: tiangular_update
upto_hop: 32
